Adding custom_reports_dir back in. Automatic build version generation.

diff --git a/.rapid/build b/.rapid/build
--- a/.rapid/build
+++ b/.rapid/build
@@ -56,7 +56,18 @@ function release_build() {
     if [[ ${is_release_branch} -eq 1 ]]
     then
         buildStepNotify 'rapidBuild'
-        
+        generate_build_version ${commit} 'true'
+        if [[ "${BUILD_VERSION}" == "" ]]
+        then
+            fail "Failed to generate build version"
+        fi
+
+        perl -pie "s/^(__version__ = ').*('.*)/\$1${BUILD_VERSION}\$2/" rapid/lib/version.py
+        if [[ $? -ne 0 ]]
+        then
+            fail "Failed to set version in version.py"
+        fi
+
         if [[ ${push_live} -eq 1 ]]
         then
             version=`python setup.py sdist upload -r pypi|grep 'Submitting dist'| awk '{print $2}'|awk -F'/' '{print $2}'|awk -F'.tar.gz' '{print $1}'|awk -F'-' '{print $3}'`
